# Generated by Django 3.2.3 on 2021-06-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('Suggestion', models.CharField(max_length=50)),
                ('Rating', models.IntegerField(default=5)),
            ],
        ),
    ]
