# Generated by Django 3.2.3 on 2021-06-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPEviewer', '0002_ppeviwer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppeviwer',
            name='pm',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
